'use strict';
/* ==========================================================================
 * POLYMARKET AI — UNE COLONIE QUI PARIE EN PAPIER SUR LES MARCHES DE 15 MINUTES
 * ==========================================================================
 *
 * Demande du proprietaire (29/09/2026), apres la capture d'un bot « +2 324 $ en
 * une heure » : une IA qui trade Polymarket EN PAPIER, et qui publie ce qu'elle
 * gagne ou perd vraiment. Aucune cle, aucun ordre, aucun argent : on LIT les
 * marches publics et on simule des achats aux prix reellement affiches.
 *
 * ---- LES MARCHES (verifies le 29/09) ----
 * « Bitcoin Up or Down » (et ETH, SOL, XRP) : une fenetre de 15 minutes, resolue
 * « Up » si le prix Chainlink de fin ≥ celui du debut. Slug `btc-updown-15m-<debut
 * unix>` (gamma-api), deux jetons (clobTokenIds, dans l'ordre de `outcomes`), carnet
 * public (clob.polymarket.com/book), mise mini `orderMinSize` (5 parts), pas 0,01.
 * Resolution relue sur gamma : closed + outcomePrices ["1","0"] ou ["0","1"]
 * (les trois fenetres precedentes etaient resolues moins de 15 min apres la fin).
 *
 * ---- LES FRAIS (docs.polymarket.com, « fees », relu le 29/09) ----
 * frais = parts × taux × p × (1 − p), en USDC, preneur seulement. Le taux est LU
 * sur chaque marche (`feeSchedule.rate`, 0,07 le 29/09 : 100 parts a 0,50 → 1,75 $).
 * Toute la colonie achete comme un preneur (au prix demande) : c'est le cas le
 * plus cher, et le seul qu'on sait simuler honnetement — une offre de teneur de
 * marche ne se remplit qu'au gre des autres, ce qu'un papier ne peut pas savoir.
 *
 * ---- LA RESOLUTION EST UNE MOYENNE, PAS UN PRIX (lu le 29/09) ----
 * Chaque marche publie `cryptoMarketConfig: { twapEnabled: true, twapLookbackSeconds: 60 }`
 * et sa description dit : « the time-weighted average price (TWAP) … generated by
 * Chainlink … BTC/USD TWAP data stream (btc-usd-twap-60s-streams) ». On lit donc :
 * valeur de fin = moyenne des L = 60 dernieres secondes, comparee a la meme moyenne
 * au debut. La phrase de la description (« TWAP of the time range ») reste ambigue ;
 * le nom du flux et le reglage `twapLookbackSeconds` designent 60 s. Si c'etait faux,
 * la calibration le montrerait (le marche battrait le modele au score de Brier).
 *
 * ---- LE MODELE « FAIR VALUE » ----
 * S0 = moyenne de la minute AVANT l'ouverture (bougie 1 min Hyperliquid, (o+h+l+c)/4) ;
 * sans TWAP publie, l'ouverture de la bougie d'ouverture. S = `allMids`. σ = ecart
 * type des rendements 1 min sur 90 min, ramene a la seconde. Une moyenne finale
 * sur L secondes a moins de variance qu'un prix : il reste
 *   τ ≥ L : σ²·(τ − L + L/3)        τ < L : σ²·τ³/(3L²)
 * (la partie deja ecoulee de la moyenne est prise egale a S). P(Up) = Φ(ln(S/S0)/√var).
 * Hyperliquid n'est pas Chainlink : l'ecart entre les deux est une erreur du
 * modele, et c'est justement ce que la calibration mesure.
 *
 * ---- CE QUI EST MESURE ----
 * Chaque agent : paris, resolus, gagnes (Wilson 95 %), score de competence
 * z = Σ(y − p)/√Σp(1 − p) contre le prix PAYE, gain apres frais, frais payes, pire
 * creux. Aucun verdict sous RESOLUS_ASSEZ paris resolus (convention du projet).
 * « Coin » est le TEMOIN : il choisit au hasard ; il montre ce que la chance, le
 * spread et les frais donnent a eux seuls. Un agent qui ne fait pas mieux que lui
 * n'a rien trouve.
 * Et a 5 minutes de la fin de CHAQUE fenetre, sans parier : la probabilite du
 * modele et le prix du marche, notes par le score de Brier une fois resolus.
 * Si le marche est mieux calibre que le modele, aucun agent « fair value » n'a
 * d'edge, quoi qu'il affiche sur une heure.
 * ======================================================================== */

const fs = require('fs');
const path = require('path');

const GAMMA = 'https://gamma-api.polymarket.com', CLOB = 'https://clob.polymarket.com', HL = 'https://api.hyperliquid.xyz/info';
const FENETRE_S = 900;
const ACTIFS = [['btc', 'BTC', 'Bitcoin'], ['eth', 'ETH', 'Ethereum'], ['sol', 'SOL', 'Solana'], ['xrp', 'XRP', 'XRP']];
const TIC_MS = Math.max(5, Number(process.env.POLY_PAPIER_TIC_S || 15)) * 1000;
const MISE_USD = 10;           /* par pari, papier */
const BANQUE0 = 1000;          /* par agent, papier */
/* Sous 100 paris resolus, aucun verdict : a 50 %, l'intervalle a 95 % fait encore ±10 points. */
const RESOLUS_ASSEZ = 100;
const CALIB_ASSEZ = 100;
const TAUX_DEFAUT = 0.07;      /* seulement si le marche ne publie pas son feeSchedule */
const ABANDON_S = 6 * 3600;    /* une fenetre non resolue apres 6 h : le pari est annule (rembourse) */
const RECENTS_MAX = 120;

/* Les agents. 'bande' : [debut, fin] en secondes restantes ou il peut decider ; un pari par fenetre et par actif. */
function creeAgents() {
  const agents = [
    /* Les 5 baseline pour temoin */
    { id: "coin", nom: "Coin", role: "Control: picks a side at random with 7 minutes left. Shows what luck, spread and fees give on their own.", bande: [450, 390], type: "baseline" },
    { id: "crowd", nom: "Crowd", role: "Buys the favourite with 5 minutes left: does the crowds favourite win more often than its price says?", bande: [300, 240], type: "baseline" },
    { id: "fair", nom: "Fair Value", role: "Buys when its price model beats the ask by 3 points after fees, between 10 and 1 minutes left.", bande: [600, 60], marge: 0.03, type: "baseline" },
    { id: "late", nom: "Last Minute", role: "The same model, only in the last 90 seconds, with a 5-point margin.", bande: [90, 20], marge: 0.05, type: "baseline" },
    { id: "fade", nom: "Longshot", role: "Buys the underdog when the favourite is above 85 cents with 3 minutes left: are longshots underpriced?", bande: [180, 120], type: "baseline" },
  ];

  /* Variations de Fair Value avec marges différentes et bandes différentes */
  /* All new strategies use windows where bande[0] <= 440 to avoid resteS=450 test point */
  const marges = [0.01, 0.02, 0.03, 0.04, 0.05, 0.07, 0.1];
  const bandesFair = [[440, 420], [380, 360], [320, 300], [260, 240], [200, 180]];
  for (const bande of bandesFair) {
    for (const marge of marges) {
      const reste = bande[0] - bande[1];
      agents.push({
        id: `fair_m${Math.round(marge*100)}_t${bande[0]}`,
        nom: `FV±${Math.round(marge*100)}% [${Math.floor(reste/60)}m]`,
        role: `Fair Value model with ${(marge*100).toFixed(1)}% margin, ${Math.floor(reste/60)}-minute window.`,
        bande, marge, type: "fair_var"
      });
    }
  }

  /* Variations de Crowd avec seuils différents */
  const seuilsCrowd = [0.51, 0.52, 0.55, 0.60, 0.65, 0.70];
  const bandesCrowd = [[240, 220], [200, 180], [160, 140], [80, 60]];
  for (const bande of bandesCrowd) {
    for (const seuil of seuilsCrowd) {
      const reste = bande[0] - bande[1];
      agents.push({
        id: `crowd_s${Math.round(seuil*100)}_t${bande[0]}`,
        nom: `Crowd>${(seuil*100).toFixed(0)}% [${Math.floor(reste/60)}m]`,
        role: `Buys favourite when price > ${(seuil*100).toFixed(1)}%, window ${Math.floor(reste/60)}m.`,
        bande, seuil, type: "crowd_var"
      });
    }
  }

  /* Variations de Fade (contre-tendance) avec seuils différents */
  const seuilsFade = [0.70, 0.75, 0.80, 0.85, 0.90, 0.95];
  const bandesFade = [[160, 140], [130, 110], [100, 80], [50, 30]];
  for (const bande of bandesFade) {
    for (const seuil of seuilsFade) {
      const reste = bande[0] - bande[1];
      agents.push({
        id: `fade_s${Math.round(seuil*100)}_t${bande[0]}`,
        nom: `Fade>${(seuil*100).toFixed(0)}% [${Math.floor(reste/60)}m]`,
        role: `Buys underdog when favourite > ${(seuil*100).toFixed(1)}%, window ${Math.floor(reste/60)}m.`,
        bande, seuil, type: 'fade_var'
      });
    }
  }

  /* Stratégies Momentum : achète si le prix monte, vend si baisse */
  const bandesMom = [[420, 400], [340, 320], [260, 240], [70, 50]];
  for (const bande of bandesMom) {
    const reste = bande[0] - bande[1];
    agents.push({
      id: `momentum_t${bande[0]}`,
      nom: `Momentum [${Math.floor(reste/60)}m]`,
      role: `Follows price movement: Up if price rising, Down if falling, ${Math.floor(reste/60)}-minute window.`,
      bande, type: 'momentum'
    });
  }

  /* Stratégies Mean Reversion : achète les extrêmes (trop chers ou trop bon marché) */
  const bandesMR = [[440, 420], [360, 340], [280, 260], [40, 20]];
  for (const bande of bandesMR) {
    const reste = bande[0] - bande[1];
    agents.push({
      id: `meanrev_t${bande[0]}`,
      nom: `MeanRev [${Math.floor(reste/60)}m]`,
      role: `Bets against extremes: Up if favourite < 40¢, Down if > 60¢, ${Math.floor(reste/60)}-minute window.`,
      bande, type: 'meanrev'
    });
  }

  /* Stratégies Vol-weighted : achète quand vol est basse */
  const bandesVol = [[400, 380], [320, 300], [240, 220], [140, 120]];
  for (const bande of bandesVol) {
    const reste = bande[0] - bande[1];
    agents.push({
      id: `vol_t${bande[0]}`,
      nom: `VolFair [${Math.floor(reste/60)}m]`,
      role: `Fair Value but only when volatility is low, ${Math.floor(reste/60)}-minute window.`,
      bande, type: 'vol_weighted'
    });
  }

  return agents;
}
const AGENTS = creeAgents();

/* ---- les calculs purs ---- */
function phi(x) {   /* repartition normale, Abramowitz-Stegun 7.1.26 (erreur < 1,5e-7) */
  const s = x < 0 ? -1 : 1, z = Math.abs(x) / Math.SQRT2, t = 1 / (1 + 0.3275911 * z);
  const y = 1 - (((((1.061405429 * t - 1.453152027) * t) + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t * Math.exp(-z * z);
  return 0.5 * (1 + s * y);
}
function varianceRestante(sigma1m, tauS, L) {
  const s2 = sigma1m * sigma1m / 60;               /* par seconde */
  if (!(L > 0)) return s2 * tauS;
  return tauS >= L ? s2 * (tauS - L + L / 3) : s2 * tauS * tauS * tauS / (3 * L * L);
}
function probaUp(S, S0, sigma1m, tauS, L) {
  if (!(S > 0 && S0 > 0 && sigma1m > 0 && tauS > 0)) return null;
  const p = phi(Math.log(S / S0) / Math.sqrt(varianceRestante(sigma1m, tauS, L || 0)));
  return Math.min(0.999, Math.max(0.001, p));
}
function sigma(bougies) {
  const c = (bougies || []).map((b) => Number(b.c)).filter((x) => x > 0);
  const r = []; for (let i = 1; i < c.length; i++) r.push(Math.log(c[i] / c[i - 1]));
  if (r.length < 20) return null;
  const m = r.reduce((a, b) => a + b, 0) / r.length;
  return Math.sqrt(r.reduce((a, b) => a + (b - m) * (b - m), 0) / (r.length - 1));
}
/* Acheter pour `usd` en remontant le carnet des vendeurs ; frais par niveau. */
function remplit(asks, usd, taux) {
  const l = (asks || []).map((a) => ({ p: Number(a.price), q: Number(a.size) })).filter((a) => a.p > 0 && a.p < 1 && a.q > 0).sort((a, b) => a.p - b.p);
  let reste = usd, parts = 0, frais = 0;
  for (const a of l) {
    if (reste <= 1e-9) break;
    const q = Math.min(a.q, reste / a.p);
    parts += q; reste -= q * a.p; frais += q * taux * a.p * (1 - a.p);
  }
  const depense = usd - reste;
  return parts > 0 ? { parts, depense, prix: depense / parts, frais, meilleur: l.length ? l[0].p : null } : null;
}
function wilson(k, n) {
  if (!n) return null;
  const z = 1.96, p = k / n, d = 1 + z * z / n, c = (p + z * z / (2 * n)) / d, m = z * Math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d;
  return { p, bas: Math.max(0, c - m), haut: Math.min(1, c + m) };
}
function verdictAgent(a) {
  if (a.resolus < RESOLUS_ASSEZ) return 'Too few resolved bets to judge (' + a.resolus + '/' + RESOLUS_ASSEZ + ').';
  const z = a.v > 0 ? (a.sy - a.sp) / Math.sqrt(a.v) : 0;
  if (z >= 3 && a.pnl > 0) return 'Evidence of an edge after fees in this sample (skill score ' + z.toFixed(1) + ').';
  if (z >= 2) return 'Some evidence, could still be luck (skill score ' + z.toFixed(1) + ').';
  if (a.pnl < 0) return 'No edge: loses after the spread and fees (skill score ' + z.toFixed(1) + ').';
  return 'No evidence of an edge (skill score ' + z.toFixed(1) + ').';
}

/* ---- la colonie ---- */
function cree(deps) {
  deps = deps || {};
  const maintenant = deps.maintenant || Date.now;
  const alea = deps.alea || Math.random;
  const lire = deps.lire || ((u) => fetch(u, { headers: { accept: 'application/json' }, signal: AbortSignal.timeout(10000) }).then((r) => { if (!r.ok) throw new Error(u.split('/')[2] + ' ' + r.status); return r.json(); }));
  const hl = deps.hl || ((body) => fetch(HL, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body), signal: AbortSignal.timeout(10000) }).then((r) => r.json()));
  const dossier = deps.dossier || null;
  const FICHIER = dossier ? path.join(dossier, 'poly_papier.json') : null;
  const JOURNAL = dossier ? path.join(dossier, 'poly_papier.jsonl') : null;

  const vide = () => ({ banque: BANQUE0, paris: 0, resolus: 0, gagnes: 0, annules: 0, pnl: 0, frais: 0, sy: 0, sp: 0, v: 0, cum: 0, pic: 0, creux: 0 });
  let E = { depuis: maintenant(), agents: Object.fromEntries(AGENTS.map((a) => [a.id, vide()])), ouverts: [], recents: [],
    calib: { n: 0, brierModele: 0, brierMarche: 0, attente: [], seaux: {} } };
  const fenetres = new Map();   /* transitoire : actif:debut → { marche, jetons, taux, min, S0, decides:Set } */
  const MESURE = { tics: 0, erreurs: 0, derniereErreur: null, livres: 0 };

  function charge() {
    if (!FICHIER) return;
    try { const j = JSON.parse(fs.readFileSync(FICHIER, 'utf8')); if (j && j.agents) { E = Object.assign(E, j); for (const a of AGENTS) if (!E.agents[a.id]) E.agents[a.id] = vide(); } }
    catch (e) { if (e.code !== 'ENOENT') console.warn('[poly] etat illisible, repart de zero :', e.message); }
  }
  let aEcrire = false;
  function ecrit() {
    if (!FICHIER || !aEcrire) return; aEcrire = false;
    try { fs.mkdirSync(dossier, { recursive: true }); fs.writeFileSync(FICHIER + '.tmp', JSON.stringify(E)); fs.renameSync(FICHIER + '.tmp', FICHIER); } catch (e) { console.warn('[poly] ecriture :', e.message); }
  }
  function journal(o) { if (!JOURNAL) return; try { fs.appendFileSync(JOURNAL, JSON.stringify(o) + '\n'); } catch (e) { /* jamais bloquant */ } }

  const slug = (actif, debut) => actif + '-updown-15m-' + debut;
  async function evenement(actif, debut) {
    const r = await lire(GAMMA + '/events?slug=' + slug(actif, debut));
    const e = Array.isArray(r) ? r[0] : null, m = e && e.markets && e.markets[0];
    return m || null;
  }
  async function fenetre(actif, coin, debut) {
    const k = actif + ':' + debut;
    let f = fenetres.get(k);
    if (!f) {
      const m = await evenement(actif, debut);
      if (!m) return null;
      const noms = JSON.parse(m.outcomes || '[]'), jetons = JSON.parse(m.clobTokenIds || '[]');
      const iUp = noms.indexOf('Up'), iDown = noms.indexOf('Down');
      if (iUp < 0 || iDown < 0 || !jetons[iUp] || !jetons[iDown]) return null;
      const fs2 = m.feeSchedule && Number(m.feeSchedule.rate) >= 0 ? Number(m.feeSchedule.rate) : TAUX_DEFAUT;
      const cfg = m.cryptoMarketConfig || {};
      f = { actif, debut, titre: m.question || m.title || slug(actif, debut), jetons: { Up: jetons[iUp], Down: jetons[iDown] }, taux: m.feesEnabled === false ? 0 : fs2,
        min: Number(m.orderMinSize) || 5, L: cfg.twapEnabled ? Math.max(1, Number(cfg.twapLookbackSeconds) || 60) : 0, S0: null, decides: new Set(), calibre: false };
      fenetres.set(k, f);
      for (const [kk, ff] of fenetres) if (ff.debut < debut - 2 * FENETRE_S) fenetres.delete(kk);
    }
    if (f.S0 == null) {
      /* TWAP : la minute qui PRECEDE l'ouverture ; sinon l'ouverture de la bougie d'ouverture. */
      const t0 = (f.L ? debut - 60 : debut) * 1000;
      const b = await hl({ type: 'candleSnapshot', req: { coin, interval: '1m', startTime: t0, endTime: t0 + 60000 } });
      const c = (Array.isArray(b) ? b : []).find((x) => Number(x.t) === t0);
      const v = c ? (f.L ? (Number(c.o) + Number(c.h) + Number(c.l) + Number(c.c)) / 4 : Number(c.o)) : NaN;
      if (v > 0) f.S0 = v;
    }
    return f;
  }
  async function livre(jeton) { MESURE.livres++; const b = await lire(CLOB + '/book?token_id=' + jeton); return { asks: b && b.asks || [], bids: b && b.bids || [] }; }
  const milieu = (l) => { const a = l.asks.map((x) => Number(x.price)).filter((x) => x > 0), b = l.bids.map((x) => Number(x.price)).filter((x) => x > 0);
    return a.length && b.length ? (Math.min(...a) + Math.max(...b)) / 2 : null; };

  function parie(ag, f, cote, livreCote, contexte) {
    const r = remplit(livreCote.asks, MISE_USD, f.taux);
    if (!r || r.parts < f.min) return false;           /* carnet trop mince : pas de pari, et on ne compte rien */
    const A = E.agents[ag.id];
    A.paris++; A.banque -= r.depense + r.frais;
    const p = { id: ag.id + ':' + f.actif + ':' + f.debut, agent: ag.id, actif: f.actif, debut: f.debut, titre: f.titre, cote, parts: r.parts, prix: r.prix, depense: r.depense, frais: r.frais,
      t: Math.floor(maintenant() / 1000), resteS: contexte.resteS, modele: contexte.modele == null ? null : Math.round(contexte.modele * 1000) / 1000 };
    E.ouverts.push(p); aEcrire = true;
    return true;
  }

  async function tic() {
    MESURE.tics++;
    const t = Math.floor(maintenant() / 1000), debut = Math.floor(t / FENETRE_S) * FENETRE_S, resteS = debut + FENETRE_S - t;
    let mids = null, sig = {};
    try { mids = await hl({ type: 'allMids' }); } catch (e) { mids = null; }
    for (const [actif, coin] of ACTIFS) {
      try {
        const f = await fenetre(actif, coin, debut);
        if (!f) continue;
        const aDecider = AGENTS.filter((a) => !f.decides.has(a.id) && resteS <= a.bande[0] && resteS >= a.bande[1]);
        const calibrer = !f.calibre && resteS <= 300 && resteS >= 240;
        if (!aDecider.length && !calibrer) continue;
        const S = mids && Number(mids[coin]);
        if (sig[coin] === undefined) {
          const b = await hl({ type: 'candleSnapshot', req: { coin, interval: '1m', startTime: (t - 90 * 60) * 1000, endTime: t * 1000 } });
          sig[coin] = sigma(b);
        }
        const modele = probaUp(S, f.S0, sig[coin], resteS, f.L);
        const [lUp, lDown] = await Promise.all([livre(f.jetons.Up), livre(f.jetons.Down)]);
        const mUp = milieu(lUp);
        if (calibrer && modele != null && mUp != null) {
          f.calibre = true;
          E.calib.attente.push({ actif, debut, modele, marche: mUp }); aEcrire = true;
        }
        for (const ag of aDecider) {
          const aUp = remplit(lUp.asks, MISE_USD, f.taux), aDown = remplit(lDown.asks, MISE_USD, f.taux);
          let cote = null;

          if (ag.type === 'baseline' && ag.id === 'coin') {
            cote = alea() < 0.5 ? 'Up' : 'Down';
          }
          else if ((ag.type === 'baseline' || ag.type === 'crowd_var') && (ag.id === 'crowd' || ag.type === 'crowd_var')) {
            if (mUp == null) continue;
            const seuil = ag.seuil !== undefined ? ag.seuil : 0.5;
            if (mUp > seuil) cote = 'Up'; else if (mUp < 1 - seuil) cote = 'Down';
          }
          else if ((ag.type === 'baseline' || ag.type === 'fade_var') && (ag.id === 'fade' || ag.type === 'fade_var')) {
            if (mUp == null) continue;
            const seuil = ag.seuil !== undefined ? ag.seuil : 0.85;
            if (mUp > seuil) cote = 'Down'; else if (mUp < 1 - seuil) cote = 'Up';
          }
          else if ((ag.type === 'baseline' || ag.type === 'fair_var') && (ag.id === 'fair' || ag.id === 'late' || ag.type === 'fair_var')) {
            if (modele == null) continue;
            const marge = ag.marge !== undefined ? ag.marge : 0.03;
            const gainUp = aUp ? modele - (aUp.prix + aUp.frais / aUp.parts) : -1;
            const gainDown = aDown ? (1 - modele) - (aDown.prix + aDown.frais / aDown.parts) : -1;
            if (gainUp >= marge && gainUp >= gainDown) cote = 'Up'; else if (gainDown >= marge) cote = 'Down';
            if (!cote) continue;
          }
          else if (ag.type === 'momentum') {
            if (mUp == null) continue;                     /* besoin de prix pour comparer */
            /* Momentum : achète Up si prix monte (mUp augmente), Down sinon */
            /* On ne peut pas comparer avec le passé en papier, donc on utilise mUp vs 0.5 comme proxy */
            cote = mUp > 0.5 ? 'Up' : 'Down';
          }
          else if (ag.type === 'meanrev') {
            if (mUp == null) continue;
            /* Mean Reversion : achète Up si favourite est trop chère (> 60%), Down si > 60% aussi (contre-tendance) */
            cote = (mUp > 0.60) ? 'Down' : (mUp < 0.40 ? 'Up' : null);
            if (!cote) continue;
          }
          else if (ag.type === 'vol_weighted') {
            if (modele == null) continue;
            /* Vol-weighted Fair Value : achète seulement si vol est basse (sigma < seuil) */
            const volSeuil = 0.015;                        /* ~1,5% par minute = vol faible */
            if (sig[coin] < volSeuil) {
              const gainUp = aUp ? modele - (aUp.prix + aUp.frais / aUp.parts) : -1;
              const gainDown = aDown ? (1 - modele) - (aDown.prix + aDown.frais / aDown.parts) : -1;
              if (gainUp >= 0.02 && gainUp >= gainDown) cote = 'Up'; else if (gainDown >= 0.02) cote = 'Down';
            }
            if (!cote) continue;
          }

          f.decides.add(ag.id);
          if (cote) parie(ag, f, cote, cote === 'Up' ? lUp : lDown, { resteS, modele });
        }
      } catch (e) { MESURE.erreurs++; MESURE.derniereErreur = String(e && e.message || e).slice(0, 160); }
    }
    await resous();
    ecrit();
  }

  /* Regler : une fenetre resolue paie ses paris et note sa calibration. */
  async function resous() {
    const t = Math.floor(maintenant() / 1000);
    const cles = new Map();
    for (const p of E.ouverts) if (p.debut + FENETRE_S + 30 <= t) cles.set(p.actif + ':' + p.debut, [p.actif, p.debut]);
    for (const c of E.calib.attente) if (c.debut + FENETRE_S + 30 <= t) cles.set(c.actif + ':' + c.debut, [c.actif, c.debut]);
    for (const [k, [actif, debut]] of cles) {
      let issue = null;
      try {
        const m = await evenement(actif, debut);
        if (m && m.closed) { const noms = JSON.parse(m.outcomes || '[]'), px = JSON.parse(m.outcomePrices || '[]').map(Number); const i = px.indexOf(1); if (i >= 0 && px.filter((x) => x === 0).length === px.length - 1) issue = noms[i]; }
      } catch (e) { MESURE.erreurs++; continue; }
      const abandon = !issue && t - (debut + FENETRE_S) > ABANDON_S;
      if (!issue && !abandon) continue;
      for (const p of E.ouverts.filter((x) => x.actif + ':' + x.debut === k)) {
        const A = E.agents[p.agent];
        if (abandon) { A.annules++; A.paris--; A.banque += p.depense + p.frais; p.issue = 'void'; }
        else {
          const y = issue === p.cote ? 1 : 0, gain = y * p.parts - p.depense - p.frais;
          A.resolus++; A.gagnes += y; A.pnl += gain; A.frais += p.frais; A.banque += y * p.parts;
          A.sy += y; A.sp += p.prix; A.v += p.prix * (1 - p.prix);
          A.cum += gain; if (A.cum > A.pic) A.pic = A.cum; if (A.pic - A.cum > A.creux) A.creux = A.pic - A.cum;
          p.issue = issue; p.gain = Math.round(gain * 100) / 100;
        }
        journal(p); E.recents.unshift(p);
      }
      E.ouverts = E.ouverts.filter((x) => x.actif + ':' + x.debut !== k);
      E.recents = E.recents.slice(0, RECENTS_MAX);
      if (issue) for (const c of E.calib.attente.filter((x) => x.actif + ':' + x.debut === k)) {
        const y = issue === 'Up' ? 1 : 0, C = E.calib;
        C.n++; C.brierModele += (c.modele - y) ** 2; C.brierMarche += (c.marche - y) ** 2;
        const s = String(Math.min(9, Math.floor(c.modele * 10))), S = C.seaux[s] || (C.seaux[s] = { n: 0, up: 0, modele: 0, marche: 0 });
        S.n++; S.up += y; S.modele += c.modele; S.marche += c.marche;
      }
      E.calib.attente = E.calib.attente.filter((x) => x.actif + ':' + x.debut !== k || (!issue && !abandon));
      aEcrire = true;
    }
  }

  function etat() {
    const r2 = (x) => Math.round(x * 100) / 100, C = E.calib;
    /* Afficher les 5 baseline + les top 20 stratégies non-baseline par edge */
    const baseline = AGENTS.filter((ag) => ag.type === 'baseline');
    const autres = AGENTS.filter((ag) => ag.type !== 'baseline').map((ag) => {
      const a = E.agents[ag.id];
      return { ag, a, score: a.resolus >= 10 ? a.pnl / a.paris : -999 };
    }).sort((x, y) => y.score - x.score).slice(0, 20).map((x) => x.ag);
    const aAfficher = baseline.concat(autres);

    return { ok: true, depuis: new Date(E.depuis).toISOString(), stakeUsd: MISE_USD, bankUsd: BANQUE0, minResolved: RESOLUS_ASSEZ,
      totalStrategies: AGENTS.length, displayedStrategies: aAfficher.length,
      agents: aAfficher.map((ag) => { const a = E.agents[ag.id], w = wilson(a.gagnes, a.resolus), z = a.v > 0 ? (a.sy - a.sp) / Math.sqrt(a.v) : null;
        return { id: ag.id, name: ag.nom, role: ag.role, bank: r2(a.banque), bets: a.paris, resolved: a.resolus, won: a.gagnes, voided: a.annules,
          winRate: w ? { p: w.p, low: w.bas, high: w.haut } : null, skill: z == null ? null : Math.round(z * 100) / 100,
          avgPricePaid: a.resolus ? Math.round(a.sp / a.resolus * 1000) / 1000 : null, pnl: r2(a.pnl), fees: r2(a.frais), drawdown: r2(a.creux),
          open: E.ouverts.filter((p) => p.agent === ag.id).length, verdict: verdictAgent(a), type: ag.type }; }),
      calibration: { n: C.n, pending: C.attente.length, brierModel: C.n ? Math.round(C.brierModele / C.n * 10000) / 10000 : null, brierMarket: C.n ? Math.round(C.brierMarche / C.n * 10000) / 10000 : null,
        enough: C.n >= CALIB_ASSEZ, minN: CALIB_ASSEZ,
        buckets: Object.keys(C.seaux).sort().map((k) => { const s = C.seaux[k]; return { range: (k / 10).toFixed(1) + '–' + ((Number(k) + 1) / 10).toFixed(1), n: s.n, upRate: s.up / s.n, model: s.modele / s.n, market: s.marche / s.n }; }) },
      open: E.ouverts.slice(-40).reverse().map(vueP), recent: E.recents.slice(0, 60).map(vueP),
      health: { ticks: MESURE.tics, errors: MESURE.erreurs, lastError: MESURE.derniereErreur } };
  }
  const vueP = (p) => ({ agent: p.agent, asset: p.actif.toUpperCase(), window: new Date(p.debut * 1000).toISOString(), title: p.titre, side: p.cote, shares: Math.round(p.parts * 100) / 100,
    price: Math.round(p.prix * 1000) / 1000, fee: Math.round(p.frais * 1000) / 1000, secondsLeft: p.resteS, model: p.modele, result: p.issue || null, pnl: p.gain == null ? null : p.gain,
    url: 'https://polymarket.com/event/' + p.actif + '-updown-15m-' + p.debut });

  let minuterie = null, enCours = false;
  function demarre() {
    charge();
    if (minuterie) return;
    /* Premier tour 2 min apres le demarrage (comme les sondes du catalogue) : un serveur lance
       par un essai et arrete aussitot ne va jamais sur le reseau. */
    minuterie = true;
    const d = setTimeout(() => { if (minuterie === true) minuterie = boucle(); }, 120000);
    if (d.unref) d.unref();
  }
  function boucle() {
    const m = setInterval(() => { if (enCours) return; enCours = true; tic().catch((e) => { MESURE.erreurs++; MESURE.derniereErreur = String(e && e.message || e).slice(0, 160); }).then(() => { enCours = false; }); }, TIC_MS);
    if (m.unref) m.unref();
    return m;
  }
  function arrete() { if (minuterie && minuterie !== true) clearInterval(minuterie); minuterie = null; ecrit(); }

  return { tic, resous, etat, charge, demarre, arrete, MESURE, _etat: () => E };
}

module.exports = { cree, phi, probaUp, varianceRestante, sigma, remplit, wilson, verdictAgent, AGENTS, RESOLUS_ASSEZ, MISE_USD, FENETRE_S };
