'use strict';
/* ==========================================================================
 * POLYMARKET AI — UNE COLONIE QUI PARIE EN PAPIER SUR LES MARCHES DE 15 MINUTES
 * ==========================================================================
 *
 * Demande du proprietaire (29/09/2026), apres la capture d'un bot « +2 324 $ en
 * une heure » : une IA qui trade Polymarket EN PAPIER, et qui publie ce qu'elle
 * gagne ou perd vraiment. Aucune cle, aucun ordre, aucun argent : on LIT les
 * marches publics et on simule des achats aux prix reellement affiches.
 *
 * ---- LES MARCHES (verifies le 29/09) ----
 * « Bitcoin Up or Down » (et ETH, SOL, XRP) : une fenetre de 15 minutes, resolue
 * « Up » si le prix Chainlink de fin ≥ celui du debut. Slug `btc-updown-15m-<debut
 * unix>` (gamma-api), deux jetons (clobTokenIds, dans l'ordre de `outcomes`), carnet
 * public (clob.polymarket.com/book), mise mini `orderMinSize` (5 parts), pas 0,01.
 * Resolution relue sur gamma : closed + outcomePrices ["1","0"] ou ["0","1"]
 * (les trois fenetres precedentes etaient resolues moins de 15 min apres la fin).
 *
 * ---- LES FRAIS (docs.polymarket.com, « fees », relu le 29/09) ----
 * frais = parts × taux × p × (1 − p), en USDC, preneur seulement. Le taux est LU
 * sur chaque marche (`feeSchedule.rate`, 0,07 le 29/09 : 100 parts a 0,50 → 1,75 $).
 * Toute la colonie achete comme un preneur (au prix demande) : c'est le cas le
 * plus cher, et le seul qu'on sait simuler honnetement — une offre de teneur de
 * marche ne se remplit qu'au gre des autres, ce qu'un papier ne peut pas savoir.
 *
 * ---- LA RESOLUTION EST UNE MOYENNE, PAS UN PRIX (lu le 29/09) ----
 * Chaque marche publie `cryptoMarketConfig: { twapEnabled: true, twapLookbackSeconds: 60 }`
 * et sa description dit : « the time-weighted average price (TWAP) … generated by
 * Chainlink … BTC/USD TWAP data stream (btc-usd-twap-60s-streams) ». On lit donc :
 * valeur de fin = moyenne des L = 60 dernieres secondes, comparee a la meme moyenne
 * au debut. La phrase de la description (« TWAP of the time range ») reste ambigue ;
 * le nom du flux et le reglage `twapLookbackSeconds` designent 60 s. Si c'etait faux,
 * la calibration le montrerait (le marche battrait le modele au score de Brier).
 *
 * ---- LE MODELE « FAIR VALUE » ----
 * S0 = moyenne de la minute AVANT l'ouverture (bougie 1 min Hyperliquid, (o+h+l+c)/4) ;
 * sans TWAP publie, l'ouverture de la bougie d'ouverture. S = `allMids`. σ = ecart
 * type des rendements 1 min sur 90 min, ramene a la seconde. Une moyenne finale
 * sur L secondes a moins de variance qu'un prix : il reste
 *   τ ≥ L : σ²·(τ − L + L/3)        τ < L : σ²·τ³/(3L²)
 * (la partie deja ecoulee de la moyenne est prise egale a S). P(Up) = Φ(ln(S/S0)/√var).
 * Hyperliquid n'est pas Chainlink : l'ecart entre les deux est une erreur du
 * modele, et c'est justement ce que la calibration mesure.
 *
 * ---- CE QUI EST MESURE ----
 * Chaque agent : paris, resolus, gagnes (Wilson 95 %), score de competence
 * z = Σ(y − p)/√Σp(1 − p) contre le prix PAYE, gain apres frais, frais payes, pire
 * creux. Aucun verdict sous RESOLUS_ASSEZ paris resolus (convention du projet).
 * « Coin » est le TEMOIN : il choisit au hasard ; il montre ce que la chance, le
 * spread et les frais donnent a eux seuls. Un agent qui ne fait pas mieux que lui
 * n'a rien trouve.
 * Et a 5 minutes de la fin de CHAQUE fenetre, sans parier : la probabilite du
 * modele et le prix du marche, notes par le score de Brier une fois resolus.
 * Si le marche est mieux calibre que le modele, aucun agent « fair value » n'a
 * d'edge, quoi qu'il affiche sur une heure.
 * ======================================================================== */

const fs = require('fs');
const path = require('path');
const polySt = require('./poly_strategies');

const GAMMA = 'https://gamma-api.polymarket.com', CLOB = 'https://clob.polymarket.com', HL = 'https://api.hyperliquid.xyz/info';
/* ---- LE CONTROLE CONTRE LES VRAIS ECHANGES (30/09/2026) ----
 * Question du proprietaire : « comment verifier que les marches ou on mise existent reellement
 * sur Polymarket et qu on pourra reellement miser avec ces strategies ? ». Le marche, le carnet
 * et la resolution viennent deja de Polymarket (gamma, CLOB). Ce qui manquait : savoir si notre
 * prix aurait ete OBTENU. Apres chaque reglement, on lit les echanges reels du marche
 * (data-api, /trades) et, pour chaque pari : y a-t-il eu une vraie execution de notre cote a
 * notre prix (+1 ¢) dans les 15 s apres la decision ? et quel gain au PREMIER prix reellement
 * echange apres elle (dans les 30 s) ? Controle a la main du 30/09 sur les 60 derniers paris :
 * 60 marches existants, 60 resolutions identiques, echanges reels dans la minute pour tous,
 * 16 734 $ echanges sur la fenetre BTC — mais dans la derniere minute le prix du Down passait
 * de 0,73 a 0,99 : la latence y coute cher, c est ce que ce controle chiffre. */
const DATA = 'https://data-api.polymarket.com';
const REEL_DELAI_S = 15, REEL_APRES_S = 30, REEL_TOLERANCE = 0.01, REEL_PAGES = 5;
/* ---- LE CARNET RELU APRES LE DELAI D UN VRAI ORDRE (30/09/2026) ----
 * Premier controle en ligne (XRP, fenetre de 17 h 15 UTC) : 166 paris, 40 echanges reels et
 * 335 $ sur toute la fenetre ; 124 paris sans aucun echange de leur cote dans les 30 s. Mais
 * « personne d autre n a achete » ne dit pas « on n aurait pas ete servi » : l offre etait dans
 * le carnet. Ce qui compte pour un vrai ordre, c est le carnet AU MOMENT OU IL ARRIVE. Chaque
 * tic qui a parie relit donc, DELAI_ORDRE_MS plus tard, le carnet des cotes achetes, et chaque
 * pari recoit le prix qu il aurait paye a ce moment-la (ou « plus rien a vendre »). Ce controle
 * couvre TOUS les paris, meme la ou personne n echange.
 * DELAI_ORDRE_MS : hypothese, pas mesure — le temps de signer et poster un ordre depuis un
 * serveur, pris large. */
const DELAI_ORDRE_MS = 2000;
const FENETRE_S = 900;
const ACTIFS = [['btc', 'BTC', 'Bitcoin'], ['eth', 'ETH', 'Ethereum'], ['sol', 'SOL', 'Solana'], ['xrp', 'XRP', 'XRP']];
const TIC_MS = Math.max(5, Number(process.env.POLY_PAPIER_TIC_S || 15)) * 1000;
const MISE_USD = 10;           /* par pari, papier */
const BANQUE0 = 1000;          /* par agent, papier */
/* Sous 100 paris resolus, aucun verdict : a 50 %, l'intervalle a 95 % fait encore ±10 points. */
const RESOLUS_ASSEZ = 100;
const CALIB_ASSEZ = 100;
/* ---- LE SCORE PAR FENETRE (30/09/2026) ----
 * Mesure du 30/09 (Hyperliquid, bougies de 15 min, 3 jours, 289 fenetres) : BTC, ETH, SOL et
 * XRP finissent dans le meme sens 72 % du temps ; correlation moyenne des issues 0,69. Deux
 * paris pris dans la meme fenetre sur deux actifs ne sont donc pas deux observations. Le score
 * par pari z = Σ(y − p)/√Σp(1 − p) les comptait comme independants : « P·FV 0.5pt ·
 * 10:00–8:00 » affichait 3,15 et « Evidence of an edge » sur 100 paris, ce que la correlation
 * ramene vers 1,8–2,2 a 2 a 4 paris par fenetre.
 * Score par fenetre : s = Σ(y − p) sur les paris d une meme fenetre (tous actifs), puis
 * zF = Σs / √Σs² (variance en grappes, robuste a la correlation entre actifs). Compte a partir
 * du 30/09 seulement : pour les strategies deja en tete, c est un echantillon NEUF, pris apres
 * leur selection — le seul qui puisse confirmer.
 * FENETRES_ASSEZ : regle usuelle, pas une mesure — la variance en grappes est trop optimiste
 * sous une cinquantaine de grappes. */
const FENETRES_ASSEZ = 50;
/* Le seuil qui tient compte du nombre de strategies essayees (Bonferroni, 5 % unilateral) :
 * sur N strategies SANS avantage, la probabilite qu une seule le depasse par hasard est ≤ 5 %.
 * 405 essayees : 3,67 ; les 2 460 + les 100 a la main : ~4,1. Plus on en essaie, plus la barre
 * monte — c est le prix de la recherche, et ce qui rend un resultat qui la passe credible. */
function barre(n) {
  const cible = 0.05 / Math.max(1, n);
  let bas = 0, haut = 10;
  for (let i = 0; i < 60; i++) { const m = (bas + haut) / 2; if (1 - phi(m) > cible) bas = m; else haut = m; }
  return haut;
}
const zFenetre = (a) => (a.nf && a.fs2 > 0 ? a.fs / Math.sqrt(a.fs2) : null);
const rz = (A) => { const z = zFenetre(A); return z == null ? null : Math.round(z * 100) / 100; };
const TAUX_DEFAUT = 0.07;      /* seulement si le marche ne publie pas son feeSchedule */
const ABANDON_S = 6 * 3600;    /* une fenetre non resolue apres 6 h : le pari est annule (rembourse) */
const RECENTS_MAX = 120;
const SIG_REF_POIDS = 1 / 1000;

/* Les agents. 'bande' : [debut, fin] en secondes restantes ou il peut decider ; un pari par fenetre et par actif. */
/* ---- LES STRATEGIES PARAMETRIQUES : 100 COMPORTEMENTS DISTINCTS ----
 * Mesure du 30/09/2026 sur poly_strategies.js : 110 700 combinaisons, mais trois
 * de ses axes — Kelly, prise de profit, stop-loss — ne sont PAS simules ici
 * (mise fixe de MISE_USD pour tous, position gardee jusqu a l echeance). Une
 * fois ces trois axes retires, il reste 2 460 comportements distincts.
 *
 * La version precedente chargeait « les 100 meilleures par edge » : le
 * classement ne recevait jamais de resultat (compteurs a zero), il rendait donc
 * toujours les 100 PREMIERES de la liste — cent fois Fair Value 0,5 % sur
 * 10–8 min, ne differant que par ces trois axes — et aucune ne pariait : le
 * type 'parametric' n etait traite nulle part dans la decision.
 *
 * Ici : 100 comportements distincts, repartis sur les six types au prorata de
 * leur nombre, parametres et fenetres pris a intervalles reguliers. L identifiant
 * est l empreinte de ce qui est simule : il survit aux redemarrages. « Les
 * meilleures par edge » se lisent ensuite sur la page, a partir de leurs propres
 * paris resolus — jamais avant RESOLUS_ASSEZ. */
const PARAM_N = 100;
const empreinte = (c) => require('crypto').createHash('sha1').update(JSON.stringify(c)).digest('hex').slice(0, 10);
function choisisParametriques(toutes, n) {
  const vus = new Map();
  for (const s of toutes) {
    const { kelly, profitTarget, stopLoss, banque0, ...simule } = s.config;   // eslint-disable-line no-unused-vars
    const k = JSON.stringify(simule);
    if (!vus.has(k)) vus.set(k, simule);
  }
  const parType = new Map();
  for (const c of vus.values()) { if (!parType.has(c.type)) parType.set(c.type, []); parType.get(c.type).push(c); }
  /* Quotas au prorata, plus grands restes. */
  const q = [...parType].map(([t, l]) => { const x = n * l.length / vus.size; return { t, l, k: Math.floor(x), r: x - Math.floor(x) }; });
  let manque = n - q.reduce((a, x) => a + x.k, 0);
  for (const x of q.slice().sort((a, b) => b.r - a.r)) { if (manque <= 0) break; x.k++; manque--; }
  const choisis = [];
  for (const x of q) for (let i = 0; i < x.k; i++) choisis.push(x.l[Math.floor(i * x.l.length / x.k)]);
  return { choisis, pool: [...vus.values()], distincts: vus.size, combinaisons: toutes.length };
}
const PARAM = choisisParametriques(polySt.creeStrategies(), PARAM_N);

/* L empreinte se calcule une fois par objet : tirer un neuf parcourt les 2 460 a chaque fois. */
const IDS = new WeakMap();
const idParam = (c) => { let i = IDS.get(c); if (!i) { i = 'p_' + empreinte(c); IDS.set(c, i); } return i; };
const agentParam = (c) => ({ id: idParam(c), nom: nomParam(c), role: roleParam(c), bande: c.fenetre, type: 'parametric', config: c });

/* ---- LE TOURNOI (30/09/2026, regle du proprietaire) ----
 * « Au bout de 500 bets, s il est toujours en negatif, l agent se supprime et un nouveau,
 * avec des parametres jamais essayes, apparait ; retenir tous les agents et parametres
 * essayes ; en faire tourner beaucoup plus. »
 * - Juge a SEUIL_TOURNOI paris REGLES (le gain n existe qu une fois regle) : en perte, il
 *   est retire ; en gain, il est rejuge 500 plus loin (1 000, 1 500…), pour qu une chance
 *   de depart ne suffise pas a rester. Les 5 d origine ne sont jamais juges : ce sont les
 *   temoins (Coin mesure ce que coutent le spread et les frais).
 * - Chaque place liberee recoit un comportement JAMAIS essaye, tire au hasard parmi les
 *   2 460 distincts. Tout retire va dans le registre `essayes`, avec son bilan.
 * - Un retire ne mise plus, mais garde ses paris ouverts jusqu a leur reglement : son
 *   bilan au registre est donc complet.
 * Mesures du 30/09 (16 h UTC, en ligne) : 9,3 paris regles par heure et par strategie
 * parametrique, soit ~2 jours 1/4 pour atteindre 500 ; journal ~14 Mo/jour pour 195
 * strategies — les paris des strategies du tournoi n y sont plus ecrits un par un, le
 * registre fait foi. SLOTS_STRATEGIES : 400 (contre 195), hors temoins. */
const SEUIL_TOURNOI = 500;
const SLOTS_STRATEGIES = 400;

const cents = (x) => Math.round(x * 100) + '¢';
function nomParam(c) {
  const w = ' · ' + fen(c.fenetre), f = (c.volFilter ? ' · calm' : '') + (c.priceFilter ? ' · 10–90¢' : '');
  switch (c.type) {
    case 'fair_value': return 'P·FV ' + (c.marge * 100).toFixed(1) + 'pt' + w + f;
    case 'crowd': return 'P·Crowd>' + cents(c.seuil) + w + f;
    case 'fade': return 'P·Fade>' + cents(c.seuil) + w + f;
    case 'momentum': return 'P·Momentum ' + (c.force * 100).toFixed(1) + 'pt' + w + f;
    case 'meanrev': return 'P·MeanRev ' + cents(c.seuilBas) + '/' + cents(c.seuilHaut) + w + f;
    case 'vol_weighted': return 'P·VolFV σ<' + c.volThreshold + '×' + w + f;
  }
  return 'P·' + c.type + w;
}
function roleParam(c) {
  const w = ' Between ' + fen(c.fenetre) + '.';
  const f = (c.volFilter ? ' Skips when volatility is above its long-run average.' : '') + (c.priceFilter ? ' Never buys below 10¢ or above 90¢.' : '');
  switch (c.type) {
    case 'fair_value': return 'Fair Value: buys when the model beats the ask by ' + (c.marge * 100).toFixed(1) + ' points after fees.' + w + f;
    case 'crowd': return 'Buys the favourite when it trades above ' + cents(c.seuil) + '.' + w + f;
    case 'fade': return 'Buys the underdog when the favourite trades above ' + cents(c.seuil) + '.' + w + f;
    case 'momentum': return 'Momentum: buys the side whose price rose at least ' + (c.force * 100).toFixed(1) + ' points over the last minute.' + w + f;
    case 'meanrev': return 'Mean reversion: buys Down when Up trades above ' + cents(c.seuilHaut) + ', Up when below ' + cents(c.seuilBas) + '.' + w + f;
    case 'vol_weighted': return 'Fair Value (2-point margin), only while volatility is under ' + c.volThreshold + '× its long-run average.' + w + f;
  }
  return c.type + '.' + w;
}

/* ---- LA DECISION D UNE STRATEGIE PARAMETRIQUE ----
 * o : { mUp, modele, aUp, aDown, sig, sigRef, mUpAvant }. Rend 'Up' ou 'Down' ;
 * 'attend' si elle doit revoir la fenetre au tic suivant (donnee absente, ou
 * rien de declenche pour une regle « achete QUAND… », comme Fair Value a la
 * main) ; null si elle a regarde et ne parie pas dans cette fenetre (Crowd et
 * Fade decident une fois, comme leurs versions a la main).
 * `sigRef` : moyenne longue de σ par actif (voir SIG_REF_POIDS). `mUpAvant` :
 * le prix du Up une minute plus tot dans la MEME fenetre — sans lui, pas de
 * momentum, on attend. */
const prixNet = (a) => a.prix + a.frais / a.parts;
function decide(c, o) {
  const retente = c.type === 'fair_value' || c.type === 'vol_weighted' || c.type === 'momentum' || c.type === 'meanrev';
  const rien = retente ? 'attend' : null;
  if (c.volFilter || c.type === 'vol_weighted') {
    if (!(o.sig > 0 && o.sigRef > 0)) return 'attend';
    if (c.volFilter && o.sig > o.sigRef) return rien;
    if (c.type === 'vol_weighted' && !(o.sig < c.volThreshold * o.sigRef)) return rien;
  }
  let cote = null;
  if (c.type === 'fair_value' || c.type === 'vol_weighted') {
    if (o.modele == null) return 'attend';
    const marge = c.type === 'vol_weighted' ? 0.02 : c.marge;
    const gU = o.aUp ? o.modele - prixNet(o.aUp) : -1, gD = o.aDown ? (1 - o.modele) - prixNet(o.aDown) : -1;
    if (gU >= marge && gU >= gD) cote = 'Up'; else if (gD >= marge) cote = 'Down';
  } else {
    if (o.mUp == null) return 'attend';
    if (c.type === 'crowd') { if (o.mUp > c.seuil) cote = 'Up'; else if (o.mUp < 1 - c.seuil) cote = 'Down'; }
    else if (c.type === 'fade') { if (o.mUp > c.seuil) cote = 'Down'; else if (o.mUp < 1 - c.seuil) cote = 'Up'; }
    else if (c.type === 'meanrev') { if (o.mUp > c.seuilHaut) cote = 'Down'; else if (o.mUp < c.seuilBas) cote = 'Up'; }
    else if (c.type === 'momentum') {
      if (o.mUpAvant == null) return 'attend';
      const d = o.mUp - o.mUpAvant;
      if (d >= c.force) cote = 'Up'; else if (d <= -c.force) cote = 'Down';
    } else return null;
  }
  if (cote && c.priceFilter) { const a = cote === 'Up' ? o.aUp : o.aDown; if (!a || a.prix < 0.10 || a.prix > 0.90) cote = null; }
  return cote || rien;
}

/* Une fenetre en clair : « 7:20–7:00 left ». Les noms disaient « [0m] » : la
   plupart des bandes font 20 s, arrondies a zero minute. */
const mmss = (s) => Math.floor(s / 60) + ':' + String(s % 60).padStart(2, '0');
const fen = (b) => mmss(b[0]) + '–' + mmss(b[1]) + ' left';

function creeAgents() {
  const agents = [
    /* Les 5 baseline pour temoin */
    { id: "coin", nom: "Coin", role: "Control: picks a side at random with 7 minutes left. Shows what luck, spread and fees give on their own.", bande: [450, 390], type: "baseline" },
    { id: "crowd", nom: "Crowd", role: "Buys the favourite with 5 minutes left: does the crowds favourite win more often than its price says?", bande: [300, 240], type: "baseline" },
    { id: "fair", nom: "Fair Value", role: "Buys when its price model beats the ask by 3 points after fees, between 10 and 1 minutes left.", bande: [600, 60], marge: 0.03, type: "baseline" },
    { id: "late", nom: "Last Minute", role: "The same model, only in the last 90 seconds, with a 5-point margin.", bande: [90, 20], marge: 0.05, type: "baseline" },
    { id: "fade", nom: "Longshot", role: "Buys the underdog when the favourite is above 85 cents with 3 minutes left: are longshots underpriced?", bande: [180, 120], type: "baseline" },
  ];

  /* Variations de Fair Value avec marges différentes et bandes différentes */
  /* All new strategies use windows where bande[0] <= 440 to avoid resteS=450 test point */
  const marges = [0.01, 0.02, 0.03, 0.04, 0.05, 0.07, 0.1];
  const bandesFair = [[440, 420], [380, 360], [320, 300], [260, 240], [200, 180]];
  for (const bande of bandesFair) {
    for (const marge of marges) {
      agents.push({
        id: `fair_m${Math.round(marge*100)}_t${bande[0]}`,
        nom: `FV±${Math.round(marge*100)}% · ${fen(bande)}`,
        role: `Fair Value model with a ${(marge*100).toFixed(1)}-point margin after fees, between ${fen(bande)}.`,
        bande, marge, type: "fair_var"
      });
    }
  }

  /* Variations de Crowd avec seuils différents */
  const seuilsCrowd = [0.51, 0.52, 0.55, 0.60, 0.65, 0.70];
  const bandesCrowd = [[240, 220], [200, 180], [160, 140], [80, 60]];
  for (const bande of bandesCrowd) {
    for (const seuil of seuilsCrowd) {
      agents.push({
        id: `crowd_s${Math.round(seuil*100)}_t${bande[0]}`,
        nom: `Crowd>${(seuil*100).toFixed(0)}¢ · ${fen(bande)}`,
        role: `Buys the favourite when it trades above ${(seuil*100).toFixed(0)}¢, between ${fen(bande)}.`,
        bande, seuil, type: "crowd_var"
      });
    }
  }

  /* Variations de Fade (contre-tendance) avec seuils différents */
  const seuilsFade = [0.70, 0.75, 0.80, 0.85, 0.90, 0.95];
  const bandesFade = [[160, 140], [130, 110], [100, 80], [50, 30]];
  for (const bande of bandesFade) {
    for (const seuil of seuilsFade) {
      agents.push({
        id: `fade_s${Math.round(seuil*100)}_t${bande[0]}`,
        nom: `Fade>${(seuil*100).toFixed(0)}¢ · ${fen(bande)}`,
        role: `Buys the underdog when the favourite trades above ${(seuil*100).toFixed(0)}¢, between ${fen(bande)}.`,
        bande, seuil, type: 'fade_var'
      });
    }
  }

  /* « Momentum » a la main : il n a AUCUN historique de prix — il achete le cote
     au-dessus de 50 ¢, c est-a-dire le favori. Son texte disait « suit le
     mouvement » : corrige le 30/09, comportement et identifiant inchanges.
     Le vrai momentum est dans les parametriques (variation sur une minute). */
  const bandesMom = [[420, 400], [340, 320], [260, 240], [70, 50]];
  for (const bande of bandesMom) {
    agents.push({
      id: `momentum_t${bande[0]}`,
      nom: `Favourite>50¢ · ${fen(bande)}`,
      role: `Buys whichever side trades above 50¢ (the favourite), between ${fen(bande)}. No price history.`,
      bande, type: 'momentum'
    });
  }

  /* Stratégies Mean Reversion : achète les extrêmes (trop chers ou trop bon marché) */
  const bandesMR = [[440, 420], [360, 340], [280, 260], [40, 20]];
  for (const bande of bandesMR) {
    agents.push({
      id: `meanrev_t${bande[0]}`,
      nom: `MeanRev 40/60¢ · ${fen(bande)}`,
      role: `Bets against extremes: buys Down when Up trades above 60¢, Up when below 40¢, between ${fen(bande)}.`,
      bande, type: 'meanrev'
    });
  }

  /* Stratégies Vol-weighted : achète quand vol est basse */
  const bandesVol = [[400, 380], [320, 300], [240, 220], [140, 120]];
  for (const bande of bandesVol) {
    agents.push({
      id: `vol_t${bande[0]}`,
      nom: `VolFair · ${fen(bande)}`,
      role: `Fair Value with a 2-point margin when 1-minute volatility is under 1.5 %, between ${fen(bande)}.`,
      bande, type: 'vol_weighted'
    });
  }

  /* Les strategies parametriques : 100 comportements DISTINCTS (voir choisisParametriques). */
  for (const c of PARAM.choisis) agents.push(agentParam(c));
  return agents;
}
const AGENTS = creeAgents();
/* Les agents ecrits a la main (temoins et variations) : la liste vivante y ajoute les parametriques de l etat. */
const AGENTS_FIXES = AGENTS.filter((a) => a.type !== 'parametric');

/* ---- les calculs purs ---- */
function phi(x) {   /* repartition normale, Abramowitz-Stegun 7.1.26 (erreur < 1,5e-7) */
  const s = x < 0 ? -1 : 1, z = Math.abs(x) / Math.SQRT2, t = 1 / (1 + 0.3275911 * z);
  const y = 1 - (((((1.061405429 * t - 1.453152027) * t) + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t * Math.exp(-z * z);
  return 0.5 * (1 + s * y);
}
function varianceRestante(sigma1m, tauS, L) {
  const s2 = sigma1m * sigma1m / 60;               /* par seconde */
  if (!(L > 0)) return s2 * tauS;
  return tauS >= L ? s2 * (tauS - L + L / 3) : s2 * tauS * tauS * tauS / (3 * L * L);
}
function probaUp(S, S0, sigma1m, tauS, L) {
  if (!(S > 0 && S0 > 0 && sigma1m > 0 && tauS > 0)) return null;
  const p = phi(Math.log(S / S0) / Math.sqrt(varianceRestante(sigma1m, tauS, L || 0)));
  return Math.min(0.999, Math.max(0.001, p));
}
function sigma(bougies) {
  const c = (bougies || []).map((b) => Number(b.c)).filter((x) => x > 0);
  const r = []; for (let i = 1; i < c.length; i++) r.push(Math.log(c[i] / c[i - 1]));
  if (r.length < 20) return null;
  const m = r.reduce((a, b) => a + b, 0) / r.length;
  return Math.sqrt(r.reduce((a, b) => a + (b - m) * (b - m), 0) / (r.length - 1));
}
/* Acheter pour `usd` en remontant le carnet des vendeurs ; frais par niveau. */
function remplit(asks, usd, taux) {
  const l = (asks || []).map((a) => ({ p: Number(a.price), q: Number(a.size) })).filter((a) => a.p > 0 && a.p < 1 && a.q > 0).sort((a, b) => a.p - b.p);
  let reste = usd, parts = 0, frais = 0;
  for (const a of l) {
    if (reste <= 1e-9) break;
    const q = Math.min(a.q, reste / a.p);
    parts += q; reste -= q * a.p; frais += q * taux * a.p * (1 - a.p);
  }
  const depense = usd - reste;
  return parts > 0 ? { parts, depense, prix: depense / parts, frais, meilleur: l.length ? l[0].p : null } : null;
}
function wilson(k, n) {
  if (!n) return null;
  const z = 1.96, p = k / n, d = 1 + z * z / n, c = (p + z * z / (2 * n)) / d, m = z * Math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d;
  return { p, bas: Math.max(0, c - m), haut: Math.min(1, c + m) };
}
/* Le verdict se lit sur le score PAR FENETRE, contre la barre du nombre de strategies essayees
   (voir FENETRES_ASSEZ et barre). `essayees` : combien de strategies ont ete mises a l essai. */
function verdictAgent(a, essayees) {
  if (a.resolus < RESOLUS_ASSEZ) return 'Too few resolved bets to judge (' + a.resolus + '/' + RESOLUS_ASSEZ + ').';
  const nf = a.nf || 0;
  if (nf < FENETRES_ASSEZ) return 'Too few independent windows to judge (' + nf + '/' + FENETRES_ASSEZ + ' counted since 30 Sep): the four coins move together, so bets in the same 15 minutes count as one.';
  const z = zFenetre(a) || 0, N = Math.max(1, essayees || 1), b = barre(N), dit = 'skill ' + z.toFixed(1) + ' per window over ' + nf + ' windows';
  if (z >= b && a.pnl > 0) {
    /* Un edge de papier n est un resultat que s il tient aux prix REELLEMENT echanges (voir REEL_DELAI_S). */
    const la = a.la || 0, sur = ', above the ' + b.toFixed(1) + ' bar that testing ' + N + ' strategies requires', d = DELAI_ORDRE_MS / 1000;
    if (la < RESOLUS_ASSEZ) return 'Edge on paper: ' + dit + sur + '. Not confirmed yet: ' + la + '/' + RESOLUS_ASSEZ + ' bets re-priced on the real order book ' + d + ' s later.';
    if ((a.laReel || 0) <= 0) return 'Edge on paper only: ' + dit + sur + ', but at the order book ' + d + ' s later it makes ' + (a.laReel < 0 ? '−$' : '$') + Math.abs(a.laReel || 0).toFixed(2) + ' over ' + la + ' bets. Not tradable as is.';
    return 'Evidence of an edge after fees: ' + dit + sur + ', and it holds on the real order book ' + d + ' s later ($' + a.laReel.toFixed(2) + ' over ' + la + ' bets).';
  }
  if (z >= 2) return 'Promising, not proven: ' + dit + ', below the ' + b.toFixed(1) + ' bar that testing ' + N + ' strategies requires — could still be luck.';
  if (a.pnl < 0) return 'No edge: loses after the spread and fees (' + dit + ').';
  return 'No evidence of an edge (' + dit + ').';
}

/* ---- la colonie ---- */
function cree(deps) {
  deps = deps || {};
  const maintenant = deps.maintenant || Date.now;
  const alea = deps.alea || Math.random;
  const attente = deps.attente || ((ms) => new Promise((r) => { const x = setTimeout(r, ms); if (x.unref) x.unref(); }));
  let placesTic = null;   /* les paris du tic en cours, relus apres DELAI_ORDRE_MS */
  const lire = deps.lire || ((u) => fetch(u, { headers: { accept: 'application/json' }, signal: AbortSignal.timeout(10000) }).then((r) => { if (!r.ok) throw new Error(u.split('/')[2] + ' ' + r.status); return r.json(); }));
  const hl = deps.hl || ((body) => fetch(HL, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body), signal: AbortSignal.timeout(10000) }).then((r) => r.json()));
  const dossier = deps.dossier || null;
  const FICHIER = dossier ? path.join(dossier, 'poly_papier.json') : null;
  const JOURNAL = dossier ? path.join(dossier, 'poly_papier.jsonl') : null;

  const vide = () => ({ banque: BANQUE0, paris: 0, resolus: 0, gagnes: 0, annules: 0, pnl: 0, frais: 0, sy: 0, sp: 0, v: 0, cum: 0, pic: 0, creux: 0 });
  let E = { depuis: maintenant(), agents: Object.fromEntries(AGENTS.map((a) => [a.id, vide()])), ouverts: [], recents: [], sigRef: {},
    calib: { n: 0, brierModele: 0, brierMarche: 0, attente: [], seaux: {} } };
  const fenetres = new Map();   /* transitoire : actif:debut → { marche, jetons, taux, min, S0, decides:Set } */
  const MESURE = { tics: 0, erreurs: 0, derniereErreur: null, livres: 0 };

  function charge() {
    if (!FICHIER) return;
    try { const j = JSON.parse(fs.readFileSync(FICHIER, 'utf8')); if (j && j.agents) { E = Object.assign(E, j); for (const a of AGENTS_FIXES) if (!E.agents[a.id]) E.agents[a.id] = vide(); if (!E.sigRef) E.sigRef = {}; cacheActifs = null; tournoiPret = false; assureTournoi(); } }
    catch (e) { if (e.code !== 'ENOENT') console.warn('[poly] etat illisible, repart de zero :', e.message); }
  }
  let aEcrire = false;
  function ecrit() {
    if (!FICHIER || !aEcrire) return; aEcrire = false;
    try { fs.mkdirSync(dossier, { recursive: true }); fs.writeFileSync(FICHIER + '.tmp', JSON.stringify(E)); fs.renameSync(FICHIER + '.tmp', FICHIER); } catch (e) { console.warn('[poly] ecriture :', e.message); }
  }
  function journal(o) { if (!JOURNAL) return; try { fs.appendFileSync(JOURNAL, JSON.stringify(o) + '\n'); } catch (e) { /* jamais bloquant */ } }

  /* ---- le tournoi (voir SEUIL_TOURNOI) : la liste VIVANTE des agents ---- */
  let cacheActifs = null, tournoiPret = false;
  const estTemoin = (id) => AGENTS_FIXES.some((a) => a.id === id && a.type === 'baseline');
  function actifs() {
    if (!cacheActifs) cacheActifs = AGENTS_FIXES.filter((a) => !E.horsJeu.includes(a.id)).concat(E.params.map(agentParam));
    return cacheActifs;
  }
  function assureTournoi() {
    if (tournoiPret) return;
    tournoiPret = true;
    /* Premier demarrage du tournoi : les 100 parametriques deja en course gardent leur place
       et leur bilan ; les places libres se remplissent de comportements jamais essayes. */
    if (!Array.isArray(E.params)) E.params = PARAM.choisis.slice();
    if (!E.essayes) E.essayes = {};
    if (!Array.isArray(E.horsJeu)) E.horsJeu = [];
    if (!Array.isArray(E.retraites)) E.retraites = [];
    if (!E.fenetresDepuis) E.fenetresDepuis = maintenant();   /* debut du compte par fenetre (voir FENETRES_ASSEZ) */
    for (const c of E.params) if (!E.agents[idParam(c)]) E.agents[idParam(c)] = vide();
    complete();
  }
  function tireNeuf() {
    const pris = new Set(Object.keys(E.essayes).concat(E.params.map(idParam)));
    const libres = PARAM.pool.filter((c) => !pris.has(idParam(c)));
    return libres.length ? libres[Math.floor(alea() * libres.length)] : null;
  }
  function complete() {
    const enJeu = () => actifs().filter((a) => !estTemoin(a.id)).length;
    while (enJeu() < SLOTS_STRATEGIES) {
      const c = tireNeuf(); if (!c) break;          /* les 2 460 ont tous ete essayes : les places restent vides */
      E.params.push(c); cacheActifs = null;
      if (!E.agents[idParam(c)]) E.agents[idParam(c)] = vide();
      aEcrire = true;
    }
  }
  function retire(ag, raison) {
    const A = E.agents[ag.id];
    E.essayes[ag.id] = { name: ag.nom, type: ag.type, config: ag.config || null, bets: A.paris, resolved: A.resolus, won: A.gagnes,
      pnl: Math.round(A.pnl * 100) / 100, fees: Math.round(A.frais * 100) / 100, windows: A.nf || 0, skillPerWindow: rz(A),
      retiredAt: new Date(maintenant()).toISOString(), reason: raison, final: false };
    if (ag.type === 'parametric') E.params = E.params.filter((c) => idParam(c) !== ag.id); else E.horsJeu.push(ag.id);
    E.retraites.push(ag.id); cacheActifs = null; aEcrire = true;
    journal({ type: 'retrait', agent: ag.id, nom: ag.nom, resolus: A.resolus, pnl: A.pnl, raison, t: maintenant() });
  }
  /* Apres chaque reglement : juger ceux qui ont atteint leur palier, finaliser les retires
     dont plus aucun pari n est ouvert, remplir les places liberees. */
  function tournoi() {
    assureTournoi();
    for (const ag of actifs().slice()) {
      if (estTemoin(ag.id)) continue;
      const A = E.agents[ag.id]; if (!A) continue;
      const palier = A.palier || SEUIL_TOURNOI;
      if (A.resolus < palier) continue;
      if (A.pnl < 0) retire(ag, 'still in the red after ' + A.resolus + ' settled bets');
      else { A.palier = palier + SEUIL_TOURNOI; aEcrire = true; }
    }
    for (const id of E.retraites.slice()) {
      if (E.ouverts.some((p) => p.agent === id)) continue;
      const A = E.agents[id], r = E.essayes[id];
      if (A && r) Object.assign(r, { bets: A.paris, resolved: A.resolus, won: A.gagnes, pnl: Math.round(A.pnl * 100) / 100, fees: Math.round(A.frais * 100) / 100,
        windows: A.nf || 0, skillPerWindow: rz(A), final: true });
      delete E.agents[id]; E.retraites = E.retraites.filter((x) => x !== id); aEcrire = true;
    }
    complete();
  }

  const slug = (actif, debut) => actif + '-updown-15m-' + debut;
  /* Les echanges reels d un marche (voir REEL_DELAI_S), du plus ancien au plus recent. */
  async function echanges(cid) {
    let tout = [];
    for (let i = 0; i < REEL_PAGES; i++) {
      const b = await lire(DATA + '/trades?market=' + cid + '&limit=1000&offset=' + i * 1000);
      if (!Array.isArray(b) || !b.length) break;
      tout = tout.concat(b.map((x) => ({ o: x.outcome, t: Number(x.timestamp), p: Number(x.price), s: Number(x.size) })).filter((x) => x.t > 0 && x.p > 0 && x.p < 1));
      if (b.length < 1000) break;
    }
    return tout.sort((a, b) => a.t - b.t);
  }
  async function evenement(actif, debut) {
    const r = await lire(GAMMA + '/events?slug=' + slug(actif, debut));
    const e = Array.isArray(r) ? r[0] : null, m = e && e.markets && e.markets[0];
    return m || null;
  }
  async function fenetre(actif, coin, debut) {
    const k = actif + ':' + debut;
    let f = fenetres.get(k);
    if (!f) {
      const m = await evenement(actif, debut);
      if (!m) return null;
      const noms = JSON.parse(m.outcomes || '[]'), jetons = JSON.parse(m.clobTokenIds || '[]');
      const iUp = noms.indexOf('Up'), iDown = noms.indexOf('Down');
      if (iUp < 0 || iDown < 0 || !jetons[iUp] || !jetons[iDown]) return null;
      const fs2 = m.feeSchedule && Number(m.feeSchedule.rate) >= 0 ? Number(m.feeSchedule.rate) : TAUX_DEFAUT;
      const cfg = m.cryptoMarketConfig || {};
      f = { actif, debut, titre: m.question || m.title || slug(actif, debut), jetons: { Up: jetons[iUp], Down: jetons[iDown] }, taux: m.feesEnabled === false ? 0 : fs2,
        min: Number(m.orderMinSize) || 5, L: cfg.twapEnabled ? Math.max(1, Number(cfg.twapLookbackSeconds) || 60) : 0, S0: null, decides: new Set(), calibre: false, traces: [] };
      fenetres.set(k, f);
      for (const [kk, ff] of fenetres) if (ff.debut < debut - 2 * FENETRE_S) fenetres.delete(kk);
    }
    if (f.S0 == null) {
      /* TWAP : la minute qui PRECEDE l'ouverture ; sinon l'ouverture de la bougie d'ouverture. */
      const t0 = (f.L ? debut - 60 : debut) * 1000;
      const b = await hl({ type: 'candleSnapshot', req: { coin, interval: '1m', startTime: t0, endTime: t0 + 60000 } });
      const c = (Array.isArray(b) ? b : []).find((x) => Number(x.t) === t0);
      const v = c ? (f.L ? (Number(c.o) + Number(c.h) + Number(c.l) + Number(c.c)) / 4 : Number(c.o)) : NaN;
      if (v > 0) f.S0 = v;
    }
    return f;
  }
  async function livre(jeton) { MESURE.livres++; const b = await lire(CLOB + '/book?token_id=' + jeton); return { asks: b && b.asks || [], bids: b && b.bids || [] }; }
  const milieu = (l) => { const a = l.asks.map((x) => Number(x.price)).filter((x) => x > 0), b = l.bids.map((x) => Number(x.price)).filter((x) => x > 0);
    return a.length && b.length ? (Math.min(...a) + Math.max(...b)) / 2 : null; };

  function parie(ag, f, cote, livreCote, contexte) {
    const r = remplit(livreCote.asks, MISE_USD, f.taux);
    if (!r || r.parts < f.min) return false;           /* carnet trop mince : pas de pari, et on ne compte rien */
    const A = E.agents[ag.id];
    A.paris++; A.banque -= r.depense + r.frais;
    const p = { id: ag.id + ':' + f.actif + ':' + f.debut, agent: ag.id, actif: f.actif, debut: f.debut, titre: f.titre, cote, parts: r.parts, prix: r.prix, depense: r.depense, frais: r.frais,
      t: Math.floor(maintenant() / 1000), resteS: contexte.resteS, modele: contexte.modele == null ? null : Math.round(contexte.modele * 1000) / 1000 };
    E.ouverts.push(p); aEcrire = true;
    if (placesTic) placesTic.push({ p, f });
    return true;
  }

  async function tic() {
    MESURE.tics++;
    assureTournoi();
    placesTic = [];
    const t = Math.floor(maintenant() / 1000), debut = Math.floor(t / FENETRE_S) * FENETRE_S, resteS = debut + FENETRE_S - t;
    let mids = null, sig = {};
    try { mids = await hl({ type: 'allMids' }); } catch (e) { mids = null; }
    for (const [actif, coin] of ACTIFS) {
      try {
        const f = await fenetre(actif, coin, debut);
        if (!f) continue;
        const aDecider = actifs().filter((a) => !f.decides.has(a.id) && resteS <= a.bande[0] && resteS >= a.bande[1]);
        const calibrer = !f.calibre && resteS <= 300 && resteS >= 240;
        if (!aDecider.length && !calibrer) continue;
        const S = mids && Number(mids[coin]);
        if (sig[coin] === undefined) {
          const b = await hl({ type: 'candleSnapshot', req: { coin, interval: '1m', startTime: (t - 90 * 60) * 1000, endTime: t * 1000 } });
          sig[coin] = sigma(b);
          /* La moyenne longue de σ, par actif, que lisent les filtres de volatilite
             des parametriques : σ est deja une moyenne de 90 min ; un poids de
             1/1000 par tic de 15 s donne environ quatre heures de memoire. */
          if (sig[coin] > 0) { const r = E.sigRef[coin]; E.sigRef[coin] = r > 0 ? r + (sig[coin] - r) * SIG_REF_POIDS : sig[coin]; }
        }
        const modele = probaUp(S, f.S0, sig[coin], resteS, f.L);
        const [lUp, lDown] = await Promise.all([livre(f.jetons.Up), livre(f.jetons.Down)]);
        const mUp = milieu(lUp);
        /* Le prix du Up au fil de la fenetre : le momentum le compare a celui d une minute plus tot. */
        if (mUp != null) { f.traces.push([t, mUp]); if (f.traces.length > 80) f.traces.shift(); }
        let mUpAvant = null;
        for (const [tt, m] of f.traces) if (tt <= t - 60) mUpAvant = m;
        const aUp = remplit(lUp.asks, MISE_USD, f.taux), aDown = remplit(lDown.asks, MISE_USD, f.taux);
        if (calibrer && modele != null && mUp != null) {
          f.calibre = true;
          E.calib.attente.push({ actif, debut, modele, marche: mUp }); aEcrire = true;
        }
        for (const ag of aDecider) {
          let cote = null;

          if (ag.type === 'parametric') {
            const d = decide(ag.config, { mUp, modele, aUp, aDown, sig: sig[coin], sigRef: E.sigRef[coin], mUpAvant });
            if (d === 'attend') continue;
            cote = d;
          }

          else if (ag.type === 'baseline' && ag.id === 'coin') {
            cote = alea() < 0.5 ? 'Up' : 'Down';
          }
          else if ((ag.type === 'baseline' || ag.type === 'crowd_var') && (ag.id === 'crowd' || ag.type === 'crowd_var')) {
            if (mUp == null) continue;
            const seuil = ag.seuil !== undefined ? ag.seuil : 0.5;
            if (mUp > seuil) cote = 'Up'; else if (mUp < 1 - seuil) cote = 'Down';
          }
          else if ((ag.type === 'baseline' || ag.type === 'fade_var') && (ag.id === 'fade' || ag.type === 'fade_var')) {
            if (mUp == null) continue;
            const seuil = ag.seuil !== undefined ? ag.seuil : 0.85;
            if (mUp > seuil) cote = 'Down'; else if (mUp < 1 - seuil) cote = 'Up';
          }
          else if ((ag.type === 'baseline' || ag.type === 'fair_var') && (ag.id === 'fair' || ag.id === 'late' || ag.type === 'fair_var')) {
            if (modele == null) continue;
            const marge = ag.marge !== undefined ? ag.marge : 0.03;
            const gainUp = aUp ? modele - (aUp.prix + aUp.frais / aUp.parts) : -1;
            const gainDown = aDown ? (1 - modele) - (aDown.prix + aDown.frais / aDown.parts) : -1;
            if (gainUp >= marge && gainUp >= gainDown) cote = 'Up'; else if (gainDown >= marge) cote = 'Down';
            if (!cote) continue;
          }
          else if (ag.type === 'momentum') {
            if (mUp == null) continue;                     /* besoin de prix pour comparer */
            /* Momentum : achète Up si prix monte (mUp augmente), Down sinon */
            /* On ne peut pas comparer avec le passé en papier, donc on utilise mUp vs 0.5 comme proxy */
            cote = mUp > 0.5 ? 'Up' : 'Down';
          }
          else if (ag.type === 'meanrev') {
            if (mUp == null) continue;
            /* Mean Reversion : achète Up si favourite est trop chère (> 60%), Down si > 60% aussi (contre-tendance) */
            cote = (mUp > 0.60) ? 'Down' : (mUp < 0.40 ? 'Up' : null);
            if (!cote) continue;
          }
          else if (ag.type === 'vol_weighted') {
            if (modele == null) continue;
            /* Vol-weighted Fair Value : achète seulement si vol est basse (sigma < seuil) */
            const volSeuil = 0.015;                        /* ~1,5% par minute = vol faible */
            if (sig[coin] < volSeuil) {
              const gainUp = aUp ? modele - (aUp.prix + aUp.frais / aUp.parts) : -1;
              const gainDown = aDown ? (1 - modele) - (aDown.prix + aDown.frais / aDown.parts) : -1;
              if (gainUp >= 0.02 && gainUp >= gainDown) cote = 'Up'; else if (gainDown >= 0.02) cote = 'Down';
            }
            if (!cote) continue;
          }

          f.decides.add(ag.id);
          if (cote) parie(ag, f, cote, cote === 'Up' ? lUp : lDown, { resteS, modele });
        }
      } catch (e) { MESURE.erreurs++; MESURE.derniereErreur = String(e && e.message || e).slice(0, 160); }
    }
    await relit(placesTic); placesTic = null;
    await resous();
    tournoi();
    ecrit();
  }

  /* Voir DELAI_ORDRE_MS : ce qu un vrai ordre, arrive apres le delai, aurait paye. */
  async function relit(places) {
    if (!places || !places.length) return;
    await attente(DELAI_ORDRE_MS);
    const livres = new Map();
    for (const { p, f } of places) livres.set(f.jetons[p.cote], null);
    await Promise.all([...livres.keys()].map(async (j) => { try { livres.set(j, await livre(j)); } catch (e) { /* non relu : pari non controle */ } }));
    for (const { p, f } of places) {
      const l = livres.get(f.jetons[p.cote]); if (!l) continue;
      const r = remplit(l.asks, p.depense, f.taux);
      if (!r || r.parts < f.min) { p.prix2 = 0; continue; }          /* plus rien a vendre a ce moment-la */
      p.prix2 = r.prix; p.parts2 = r.parts; p.dep2 = r.depense; p.frais2 = r.frais;
    }
    aEcrire = true;
  }
  function realite() { return E.realite || (E.realite = { marches: 0, paris: 0, ok: 0, sans: 0, avecPrix: 0, ecartPrix: 0, papier: 0, reel: 0, volumes: [] }); }
  /* Un pari regle, contre les echanges reels qui ont suivi la decision (voir REEL_DELAI_S). */
  function controle(A, p, y, gain, reels) {
    const R = realite(), t0 = Number(p.t) || 0;
    const apres = reels.filter((x) => x.o === p.cote && x.t >= t0 && x.t <= t0 + REEL_APRES_S);
    A.ve = (A.ve || 0) + 1; R.paris++;
    if (apres.some((x) => x.t <= t0 + REEL_DELAI_S && x.p <= p.prix + REEL_TOLERANCE)) { A.veOk = (A.veOk || 0) + 1; R.ok++; }
    if (!apres.length) { A.veSans = (A.veSans || 0) + 1; R.sans++; return; }
    /* Au premier prix reellement echange : memes dollars, parts et frais recalcules a ce prix. */
    const pr = Math.min(0.99, Math.max(0.01, apres[0].p)), parts = p.depense / pr;
    const taux = p.parts > 0 && p.prix > 0 && p.prix < 1 ? p.frais / (p.parts * p.prix * (1 - p.prix)) : 0;
    const gainReel = y * parts - p.depense - parts * taux * pr * (1 - pr);
    A.vePapier = (A.vePapier || 0) + gain; A.veReel = (A.veReel || 0) + gainReel;
    R.avecPrix++; R.ecartPrix += pr - p.prix; R.papier += gain; R.reel += gainReel;
  }

  /* Regler : une fenetre resolue paie ses paris et note sa calibration. */
  async function resous() {
    const t = Math.floor(maintenant() / 1000);
    const cles = new Map();
    for (const p of E.ouverts) if (p.debut + FENETRE_S + 30 <= t) cles.set(p.actif + ':' + p.debut, [p.actif, p.debut]);
    for (const c of E.calib.attente) if (c.debut + FENETRE_S + 30 <= t) cles.set(c.actif + ':' + c.debut, [c.actif, c.debut]);
    for (const [k, [actif, debut]] of cles) {
      let issue = null, m = null;
      try {
        m = await evenement(actif, debut);
        if (m && m.closed) { const noms = JSON.parse(m.outcomes || '[]'), px = JSON.parse(m.outcomePrices || '[]').map(Number); const i = px.indexOf(1); if (i >= 0 && px.filter((x) => x === 0).length === px.length - 1) issue = noms[i]; }
      } catch (e) { MESURE.erreurs++; continue; }
      /* Les vrais echanges : jamais bloquants, un echec laisse simplement ces paris non controles. */
      let reels = null;
      if (issue && m && m.conditionId && E.ouverts.some((x) => x.actif + ':' + x.debut === k)) {
        try { reels = await echanges(m.conditionId); } catch (e) { reels = null; }
        if (reels) { const R = realite(); R.marches++; R.volumes.push([actif, Math.round(reels.reduce((t, x) => t + x.s * x.p, 0))]); if (R.volumes.length > 200) R.volumes.shift(); }
      }
      const abandon = !issue && t - (debut + FENETRE_S) > ABANDON_S;
      if (!issue && !abandon) continue;
      const touches = new Set();
      for (const p of E.ouverts.filter((x) => x.actif + ':' + x.debut === k)) {
        const A = E.agents[p.agent];
        touches.add(p.agent);
        if (abandon) { A.annules++; A.paris--; A.banque += p.depense + p.frais; p.issue = 'void'; }
        else {
          const y = issue === p.cote ? 1 : 0, gain = y * p.parts - p.depense - p.frais;
          A.resolus++; A.gagnes += y; A.pnl += gain; A.frais += p.frais; A.banque += y * p.parts;
          A.sy += y; A.sp += p.prix; A.v += p.prix * (1 - p.prix);
          /* La grappe de la fenetre (voir FENETRES_ASSEZ) : close quand tous ses paris sont regles. */
          const G = (A.gr || (A.gr = {}))[debut] || (A.gr[debut] = 0);
          A.gr[debut] = G + y - p.prix;
          if (reels) controle(A, p, y, gain, reels);
          if (p.prix2 != null) {
            const R = realite(); A.la = (A.la || 0) + 1; R.la = (R.la || 0) + 1;
            if (!p.prix2) { A.laSans = (A.laSans || 0) + 1; R.laSans = (R.laSans || 0) + 1; }
            else {
              const g2 = y * p.parts2 - p.dep2 - p.frais2;
              A.laPapier = (A.laPapier || 0) + gain; A.laReel = (A.laReel || 0) + g2;
              R.laPapier = (R.laPapier || 0) + gain; R.laReel = (R.laReel || 0) + g2; R.laEcart = (R.laEcart || 0) + p.prix2 - p.prix; R.laPrix = (R.laPrix || 0) + 1;
            }
          }
          A.cum += gain; if (A.cum > A.pic) A.pic = A.cum; if (A.pic - A.cum > A.creux) A.creux = A.pic - A.cum;
          p.issue = issue; p.gain = Math.round(gain * 100) / 100;
        }
        /* Le tournoi : le registre fait foi (volume, voir SEUIL_TOURNOI). Mais une strategie qui
           passe RESOLUS_ASSEZ en gain devient une candidate : ses paris sont de nouveau ecrits un
           par un, pour pouvoir la verifier a la main (une par pari et par fenetre). */
        if (!String(p.agent).startsWith('p_') || (A.resolus >= RESOLUS_ASSEZ && A.pnl > 0)) journal(p);
        E.recents.unshift(p);
      }
      E.ouverts = E.ouverts.filter((x) => x.actif + ':' + x.debut !== k);
      const restent = new Set(E.ouverts.filter((x) => x.debut === debut).map((x) => x.agent));
      for (const id of touches) {
        const A = E.agents[id];
        if (!A || !A.gr || !(debut in A.gr) || restent.has(id)) continue;
        const g = A.gr[debut]; delete A.gr[debut];
        A.fs = (A.fs || 0) + g; A.fs2 = (A.fs2 || 0) + g * g; A.nf = (A.nf || 0) + 1;
      }
      E.recents = E.recents.slice(0, RECENTS_MAX);
      if (issue) for (const c of E.calib.attente.filter((x) => x.actif + ':' + x.debut === k)) {
        const y = issue === 'Up' ? 1 : 0, C = E.calib;
        C.n++; C.brierModele += (c.modele - y) ** 2; C.brierMarche += (c.marche - y) ** 2;
        const s = String(Math.min(9, Math.floor(c.modele * 10))), S = C.seaux[s] || (C.seaux[s] = { n: 0, up: 0, modele: 0, marche: 0 });
        S.n++; S.up += y; S.modele += c.modele; S.marche += c.marche;
      }
      E.calib.attente = E.calib.attente.filter((x) => x.actif + ':' + x.debut !== k || (!issue && !abandon));
      aEcrire = true;
    }
  }

  function etat() {
    const r2 = (x) => Math.round(x * 100) / 100, C = E.calib;
    /* Le controle contre les vrais echanges (voir REEL_DELAI_S), par strategie et en tout. */
    const reelDe = (a) => (a.la || a.ve ? { repriced: a.la || 0, emptyBook: a.laSans || 0, paperPnl: r2(a.laPapier || 0), pnlAfterDelay: r2(a.laReel || 0),
      tradeChecked: a.ve || 0, confirmedByTrade: a.veOk || 0 } : null);
    const R = realite(), med = (l) => { const x = l.slice().sort((u, v) => u - v); return x.length ? x[x.length >> 1] : null; };
    const volumes = {}; for (const v of R.volumes) if (Array.isArray(v)) (volumes[v[0]] || (volumes[v[0]] = [])).push(v[1]);
    const reality = { orderDelaySeconds: DELAI_ORDRE_MS / 1000, repriced: R.la || 0, emptyBook: R.laSans || 0, paperPnl: r2(R.laPapier || 0), pnlAfterDelay: r2(R.laReel || 0),
      avgPriceMoveAfterDelay: R.laPrix ? Math.round(R.laEcart / R.laPrix * 1000) / 1000 : null,
      trades: { marketsChecked: R.marches, betsChecked: R.paris, confirmedAtOurPrice: R.ok, noTradeWithin: R.sans, withinSeconds: REEL_DELAI_S, nextTradeSeconds: REEL_APRES_S },
      medianVolumeUsd: Object.fromEntries(ACTIFS.map(([a]) => [a.toUpperCase(), volumes[a] ? med(volumes[a]) : null])), marketsWithVolume: Object.fromEntries(ACTIFS.map(([a]) => [a.toUpperCase(), volumes[a] ? volumes[a].length : 0])),
      rule: 'Every market, order book and result comes from Polymarket itself (each bet links to its market). A real order takes time to arrive: ' + DELAI_ORDRE_MS / 1000 +
        ' s after each decision, the real order book is read again and the bet is re-priced at what it would have paid then (or nothing left to buy). After settlement, each bet is also compared with the trades really made on Polymarket.' };
    /* LE CLASSEMENT, DU PLUS GAGNANT AU PLUS PERDANT (30/09/2026) ----
       Demande du proprietaire : « classe du plus gagnant au plus perdant, la on dirait qu il
       n y a pas d ordre ». La vue montrait les 5 d origine PUIS 20 strategies triees par gain
       MOYEN par pari — et seulement les gagnantes : 20 cartes vertes sur 195, choisies apres
       coup. Maintenant : le classement COMPLET par gain total, un resume (combien en gain, en
       perte), et en cartes les 5 d origine, les 10 meilleures et les 10 pires. */
    assureTournoi();
    const ouvertsPar = {}; for (const p of E.ouverts) ouvertsPar[p.agent] = (ouvertsPar[p.agent] || 0) + 1;
    const ligneC = (ag) => { const a = E.agents[ag.id]; return { id: ag.id, name: ag.nom, type: ag.type, bets: a.paris, resolved: a.resolus, won: a.gagnes,
      pnl: r2(a.pnl), open: ouvertsPar[ag.id] || 0, nextJudgedAt: estTemoin(ag.id) ? null : (a.palier || SEUIL_TOURNOI),
      windows: a.nf || 0, skillPerWindow: rz(a), real: reelDe(a) }; };
    const parGain = (x, y) => y.pnl - x.pnl || y.resolved - x.resolved;
    const AG = actifs();
    const classement = AG.map(ligneC).sort(parGain);
    const regles = classement.filter((c) => c.resolved > 0);
    const resume = { total: classement.length, inProfit: regles.filter((c) => c.pnl > 0).length, inLoss: regles.filter((c) => c.pnl < 0).length,
      noSettledBet: classement.length - regles.length, totalPnl: r2(classement.reduce((t, c) => t + c.pnl, 0)),
      judgeable: classement.filter((c) => c.resolved >= RESOLUS_ASSEZ).length };
    const autres = regles.filter((c) => !estTemoin(c.id));
    const choisis = new Set(AG.filter((ag) => ag.type === 'baseline').map((ag) => ag.id)
      .concat(autres.slice(0, 10).map((c) => c.id), autres.slice(-10).map((c) => c.id)));
    const aAfficher = AG.filter((ag) => choisis.has(ag.id)).sort((x, y) => E.agents[y.id].pnl - E.agents[x.id].pnl);
    const retires = Object.entries(E.essayes).map(([id, r]) => ({ id, name: r.name, type: r.type, bets: r.bets, resolved: r.resolved, won: r.won, pnl: r.pnl,
      windows: r.windows || 0, skillPerWindow: r.skillPerWindow == null ? null : r.skillPerWindow, retiredAt: r.retiredAt, reason: r.reason, final: r.final }))
      .sort((x, y) => Date.parse(y.retiredAt) - Date.parse(x.retiredAt));
    const essayesParam = new Set(Object.keys(E.essayes).filter((id) => id.startsWith('p_')).concat(E.params.map(idParam)));
    const tournament = { threshold: SEUIL_TOURNOI, slots: SLOTS_STRATEGIES, controls: AG.filter((a) => estTemoin(a.id)).length,
      running: AG.length, retired: retires.length, parametricTried: essayesParam.size, parametricUntried: PARAM.distincts - essayesParam.size,
      rule: 'A strategy still in the red after ' + SEUIL_TOURNOI + ' settled bets is retired and replaced by a parameter set never tried before; one in profit is judged again ' + SEUIL_TOURNOI + ' bets later. The 5 original agents are controls and are never retired. Surviving a check is not proof of an edge: with fees and the spread, roughly 1 strategy in 8 with no edge still passes 500 bets by luck — the skill score is what counts.',
      recentlyRetired: retires.slice(0, 30) };
    /* La preuve (voir FENETRES_ASSEZ et barre) : ou en est-on d un resultat ? Les strategies qui
       ont assez de fenetres, classees par score par fenetre, contre la barre du nombre essaye. */
    const essayees = AG.length + retires.length, b = barre(essayees);
    const mesurees = classement.filter((c) => c.windows >= FENETRES_ASSEZ && c.skillPerWindow != null)
      .sort((x, y) => y.skillPerWindow - x.skillPerWindow || y.windows - x.windows);
    const evidence = { since: new Date(E.fenetresDepuis).toISOString(), minWindows: FENETRES_ASSEZ, tested: essayees, bar: r2(b),
      measured: mesurees.length, proven: mesurees.filter((c) => c.skillPerWindow >= b && c.pnl > 0).length,
      promising: mesurees.filter((c) => c.skillPerWindow >= 2 && c.skillPerWindow < b).length,
      leaders: mesurees.slice(0, 10).map((c) => ({ id: c.id, name: c.name, windows: c.windows, skillPerWindow: c.skillPerWindow, resolved: c.resolved, pnl: c.pnl, real: c.real })),
      /* Celles qui approchent du seuil de mesure : on voit venir les prochaines a juger. */
      closest: classement.filter((c) => c.windows < FENETRES_ASSEZ).sort((x, y) => y.windows - x.windows).slice(0, 5)
        .map((c) => ({ id: c.id, name: c.name, windows: c.windows, skillPerWindow: c.skillPerWindow, pnl: c.pnl })),
      rule: 'Bets placed in the same 15 minutes count as one observation: BTC, ETH, SOL and XRP finish the same way about 72% of the time. A strategy is only measured after ' + FENETRES_ASSEZ +
        ' windows counted since ' + new Date(E.fenetresDepuis).toISOString().slice(0, 10) + ', and only called an edge above the bar set by the number of strategies tested (' + essayees + ' so far: ' + b.toFixed(2) + '), and in profit after fees.' };

    return { ok: true, depuis: new Date(E.depuis).toISOString(), stakeUsd: MISE_USD, bankUsd: BANQUE0, minResolved: RESOLUS_ASSEZ,
      totalStrategies: AG.length, displayedStrategies: aAfficher.length, ranking: classement, summary: resume, tournament, evidence, reality,
      parametric: { running: E.params.length, distinct: PARAM.distincts, combinations: PARAM.combinaisons,
        note: 'Kelly sizing, profit targets and stop-losses are not simulated: every agent stakes the same amount and holds to resolution.' },
      agents: aAfficher.map((ag) => { const a = E.agents[ag.id], w = wilson(a.gagnes, a.resolus), z = a.v > 0 ? (a.sy - a.sp) / Math.sqrt(a.v) : null;
        return { id: ag.id, name: ag.nom, role: ag.role, bank: r2(a.banque), bets: a.paris, resolved: a.resolus, won: a.gagnes, voided: a.annules,
          winRate: w ? { p: w.p, low: w.bas, high: w.haut } : null, skill: z == null ? null : Math.round(z * 100) / 100, skillPerWindow: rz(a), windows: a.nf || 0, real: reelDe(a),
          avgPricePaid: a.resolus ? Math.round(a.sp / a.resolus * 1000) / 1000 : null, pnl: r2(a.pnl), fees: r2(a.frais), drawdown: r2(a.creux),
          open: ouvertsPar[ag.id] || 0, verdict: verdictAgent(a, essayees), type: ag.type }; }),
      calibration: { n: C.n, pending: C.attente.length, brierModel: C.n ? Math.round(C.brierModele / C.n * 10000) / 10000 : null, brierMarket: C.n ? Math.round(C.brierMarche / C.n * 10000) / 10000 : null,
        enough: C.n >= CALIB_ASSEZ, minN: CALIB_ASSEZ,
        buckets: Object.keys(C.seaux).sort().map((k) => { const s = C.seaux[k]; return { range: (k / 10).toFixed(1) + '–' + ((Number(k) + 1) / 10).toFixed(1), n: s.n, upRate: s.up / s.n, model: s.modele / s.n, market: s.marche / s.n }; }) },
      open: E.ouverts.slice(-40).reverse().map(vueP), recent: E.recents.slice(0, 60).map(vueP),
      health: { ticks: MESURE.tics, errors: MESURE.erreurs, lastError: MESURE.derniereErreur } };
  }
  const vueP = (p) => ({ agent: p.agent, asset: p.actif.toUpperCase(), window: new Date(p.debut * 1000).toISOString(), title: p.titre, side: p.cote, shares: Math.round(p.parts * 100) / 100,
    price: Math.round(p.prix * 1000) / 1000, fee: Math.round(p.frais * 1000) / 1000, secondsLeft: p.resteS, model: p.modele, result: p.issue || null, pnl: p.gain == null ? null : p.gain,
    url: 'https://polymarket.com/event/' + p.actif + '-updown-15m-' + p.debut });

  let minuterie = null, enCours = false;
  function demarre() {
    charge();
    if (minuterie) return;
    /* Premier tour 2 min apres le demarrage (comme les sondes du catalogue) : un serveur lance
       par un essai et arrete aussitot ne va jamais sur le reseau. */
    minuterie = true;
    const d = setTimeout(() => { if (minuterie === true) minuterie = boucle(); }, 120000);
    if (d.unref) d.unref();
  }
  function boucle() {
    const m = setInterval(() => { if (enCours) return; enCours = true; tic().catch((e) => { MESURE.erreurs++; MESURE.derniereErreur = String(e && e.message || e).slice(0, 160); }).then(() => { enCours = false; }); }, TIC_MS);
    if (m.unref) m.unref();
    return m;
  }
  function arrete() { if (minuterie && minuterie !== true) clearInterval(minuterie); minuterie = null; ecrit(); }

  return { tic, resous, etat, charge, demarre, arrete, MESURE, _etat: () => E, _tournoi: tournoi };
}

module.exports = { cree, decide, choisisParametriques, PARAM, agentParam, SEUIL_TOURNOI, SLOTS_STRATEGIES, phi, probaUp, varianceRestante, sigma, remplit, wilson, verdictAgent, barre, FENETRES_ASSEZ, AGENTS, RESOLUS_ASSEZ, MISE_USD, FENETRE_S };
